title: Personalizing ChatGPT - Making AI Sound Like You!
hero_image: images/banner.jpg
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Prompting ChatGPT
  - title: What next?
